services:
  app:
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    build: .
    entrypoint: ["poetry", "run"]
    ports:
      - "8000:8000"
    volumes:
      - .:/app
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_ROOT_USERNAME: admin
    ports:
      - "27017:27017"
    restart: always
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    restart: always
  redis:
    image: redis
    ports:
      - "6379:6379"
