services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    restart: always
  redis:
    image: redis
    ports:
      - "6379:6379"
