# Generated by Django 4.1.4 on 2023-01-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_organization_order_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="code",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
