# Generated by Django 4.1.4 on 2023-01-13 07:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_verification_token",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
