# Generated by Django 4.1.4 on 2023-01-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_organization_code_alter_organization_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="code",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
