# Generated by Django 4.1.4 on 2023-01-29 09:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_user_email_verification_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="authentication_token",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
