# Generated by Django 4.1.4 on 2023-02-12 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_user_authentication_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="Personnel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("does_organization_agree", models.BooleanField()),
                ("does_user_agree", models.BooleanField()),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.user"
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="personnel",
            constraint=models.UniqueConstraint(
                models.F("organization"),
                models.F("user"),
                name="main_organizationuser_organization_id_user_id",
            ),
        ),
    ]
