# Generated by Django 4.1.4 on 2023-03-02 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_personnel_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_system_administrator",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
