# Generated by Django 4.1.4 on 2023-03-22 08:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_user_is_system_administrator"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="personnel",
            name="main_organizationuser_organization_id_user_id",
        ),
        migrations.AlterUniqueTogether(
            name="personnel",
            unique_together={("organization", "user")},
        ),
    ]
