# Generated by Django 4.1.4 on 2023-03-25 08:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "main",
            (
                "0008_remove_personnel_main_organizationuser_organization_id_user_id"
                "_and_more"
            ),
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Personnel",
            new_name="Staff",
        ),
        migrations.AlterUniqueTogether(
            name="staff",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="staff",
            constraint=models.UniqueConstraint(
                models.F("organization"),
                models.F("user"),
                name="main_organizationuser_organization_id_user_id",
            ),
        ),
    ]
