# Generated by Django 4.1.4 on 2023-03-26 08:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0009_rename_personnel_staff_alter_staff_unique_together_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="email_verification_token",
            new_name="email_verifying_token",
        ),
    ]
