# Generated by Django 4.1.4 on 2023-03-26 09:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0010_rename_email_verification_token_user_email_verifying_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password_resetting_token",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
