# Generated by Django 4.1.4 on 2023-04-07 06:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0014_organization_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="code",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
