# Generated by Django 4.1.4 on 2023-04-10 06:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0017_orderitem_product"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="OrderItem",
            new_name="ProductItem",
        ),
    ]
