# Generated by Django 4.1.4 on 2023-05-07 09:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0020_alter_order_code_alter_product_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="total",
            field=models.DecimalField(decimal_places=4, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name="productitem",
            name="total",
            field=models.DecimalField(decimal_places=4, max_digits=19, null=True),
        ),
    ]
