# Generated by Django 4.1.4 on 2023-05-11 03:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0022_alter_order_total_alter_productitem_total"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productshipping",
            name="fee",
        ),
        migrations.RemoveField(
            model_name="productshipping",
            name="shipping_type",
        ),
        migrations.AddField(
            model_name="productshipping",
            name="fixed_fee",
            field=models.DecimalField(decimal_places=4, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name="productshipping",
            name="products",
            field=models.ManyToManyField(to="main.product"),
        ),
        migrations.AddField(
            model_name="productshipping",
            name="unit_fee",
            field=models.DecimalField(decimal_places=4, max_digits=19, null=True),
        ),
    ]
