# Generated by Django 4.1.4 on 2023-05-11 03:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0023_remove_productshipping_fee_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productshipping",
            name="fixed_fee",
            field=models.DecimalField(decimal_places=4, max_digits=19),
        ),
        migrations.AlterField(
            model_name="productshipping",
            name="unit_fee",
            field=models.DecimalField(decimal_places=4, max_digits=19),
        ),
    ]
