# Generated by Django 4.1.4 on 2023-06-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0024_alter_productshipping_fixed_fee_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="product_total",
            field=models.DecimalField(decimal_places=4, max_digits=19, null=True),
        ),
    ]
