# Generated by Django 4.1.4 on 2023-08-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0027_productitem_item_total_productitem_subtotal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productitem",
            name="item_total",
            field=models.DecimalField(decimal_places=4, max_digits=19),
        ),
        migrations.AlterField(
            model_name="productitem",
            name="subtotal",
            field=models.DecimalField(decimal_places=4, max_digits=19),
        ),
    ]
