# Generated by Django 4.1.4 on 2023-08-06 04:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0029_productitem_shipping_total_productshippingitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productitem",
            name="shipping_total",
            field=models.DecimalField(decimal_places=4, max_digits=19),
        ),
    ]
