# Generated by Django 4.1.4 on 2023-11-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0031_ordershipping_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="productshipping",
            name="main_product_shipping_rule_code_organization_id",
        ),
        migrations.RemoveField(
            model_name="user",
            name="email_verifying_token",
        ),
        migrations.RemoveField(
            model_name="user",
            name="password_resetting_token",
        ),
        migrations.AlterField(
            model_name="productshipping",
            name="products",
            field=models.ManyToManyField(blank=True, to="main.product"),
        ),
        migrations.AddConstraint(
            model_name="productshipping",
            constraint=models.UniqueConstraint(
                models.F("code"),
                models.F("organization"),
                name="main_product_shipping_code_organization_id",
            ),
        ),
    ]
