# Generated by Django 4.2.8 on 2023-12-11 16:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "main",
            (
                "0032_remove_productshipping_main_product_shipping_rule_code"
                "_organization_id_and_more"
            ),
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="authentication_token",
        ),
    ]
