# Generated by Django 4.2.8 on 2024-01-25 08:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0033_remove_user_authentication_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productitem",
            name="shipping_total",
        ),
        migrations.RemoveField(
            model_name="productitem",
            name="subtotal",
        ),
        migrations.RemoveField(
            model_name="productitem",
            name="total",
        ),
        migrations.RemoveField(
            model_name="productshippingitem",
            name="subtotal",
        ),
        migrations.RemoveField(
            model_name="productshippingitem",
            name="total",
        ),
        migrations.AddField(
            model_name="order",
            name="product_shipping_total",
            field=models.DecimalField(decimal_places=4, max_digits=19, null=True),
        ),
    ]
