# Generated by Django 4.2.8 on 2024-01-27 12:15

from django.db import migrations
from django.db.models import Sum


def code(apps, schema_editor):
    Order = apps.get_model("main", "Order")
    db_alias = schema_editor.connection.alias
    query_set = Order.objects.using(db_alias).filter(product_shipping_total=None)
    while query_set.count() > 0:
        orders = query_set[:1000]
        data_list = (
            Order.using(db_alias)
            .objects.filter(id__in=[order.id for order in orders])
            .values("id")
            .annotate(
                product_shipping_total=Sum(
                    "productitem__productshippingitem__item_total"
                )
            )
        )
        dict_ = {data["id"]: data["product_shipping_total"] for data in data_list}
        for order in orders:
            order.product_shipping_total = dict_[order.id]
        Order.objects.using(db_alias).bulk_update(orders, ["product_shipping_total"])


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0034_remove_productitem_shipping_total_and_more"),
    ]

    operations = [migrations.RunPython(code)]
