# Generated by Django 4.2.8 on 2024-01-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0035_auto_20240127_1215"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="product_shipping_total",
            field=models.DecimalField(decimal_places=4, max_digits=19),
        ),
    ]
